# Generated by Django 4.0.4 on 2022-06-14 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Img_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgages', models.ImageField(upload_to='Image_Gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='info/')),
                ('facebook', models.URLField()),
                ('Telegram', models.URLField()),
                ('Instagram', models.URLField()),
                ('YouTube', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Introductory_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News_Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Our_Missions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='our_missions/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Strimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Twitch_Sitrim', models.IntegerField()),
                ('Strimers', models.IntegerField()),
                ('Cs_Go', models.IntegerField()),
                ('Pubg_Sitrim', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team_one_player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_team', models.ImageField(upload_to='Image_Team_One_Player/')),
                ('An_experience_1', models.IntegerField()),
                ('An_experience_2', models.IntegerField()),
                ('Surname', models.CharField(max_length=255)),
                ('Directions', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.games')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_team', models.ImageField(upload_to='Image_Team_One_Player/')),
                ('An_experience_1', models.IntegerField()),
                ('An_experience_2', models.IntegerField()),
                ('Number_Player', models.CharField(max_length=255)),
                ('Directions', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(max_length=255)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.games')),
            ],
        ),
        migrations.CreateModel(
            name='Last_Turnir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.games')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.team')),
            ],
        ),
    ]
