# Generated by Django 4.0.4 on 2022-06-14 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='last_turnir',
            name='team_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='last_turnir',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='Api.team'),
        ),
    ]
